# Generated by Django 5.1.5 on 2025-04-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tno', models.IntegerField()),
                ('tname', models.CharField(max_length=30)),
                ('sub', models.CharField(max_length=30)),
                ('sal', models.FloatField()),
            ],
        ),
    ]
